Feature: Adapted structure to HACS integration blueprint
dontinelli/fyta-custom_component pull request #4
Opened 2024-02-26 06:58 UTC by JanGiese

Hey,

Thands for creating this integration. I am looking forward to use it in my SmarHome as well, but in order to install it, I have refactored it the HACS integration blueprint structure, so it can be installed from the HACS Custom Repositories. Basically I have moved the Python files to custom_components/fyta_integration and added some descriptive files around it. I have also included the recommended dev-container which can be used for development inside a Docker Container and the GitHub Actions needed for the release into HACS. At last, I have added some docs, so the Linting Action I have added won´t complain anymore.  
I hope you´ll find it useful as well. If you have any questions, feel free to reach out to me.

2024-02-26 08:57 UTC, dontinelli commented
Thank you a lot, looks great! I only have two questions before I merge:

1. In the meanwhile I uploaded fyta_cli to Pypi. Would it make sense to add fyta_cli as a requirement instead of delivering it as part of the integration files? I'm not sure what the best practice is in this respect, but it has an influence on the import-lines.
2. With regards to maintenance, can just the files in custom_components/fyta be updated or what else has to be considered for future releases? As you may have noticed, I'm currently working on a PR to include fyta as core integration. However, the review process is rather cumbersome. So while I would like to backport some changes and also further develop the custom integration (which might be easier than bringing improvements to core), I do not have the time for extensive additional work.

2024-02-27 19:06 UTC, JanGiese commented on .devcontainer.json
> +}
This is required for the devcontainer, if I am not mistaking. The devcontainer enables development with e.g. VS Code in a container, which contains a complete HomeAssistant installation for testing. You can start it with script/./develop

2024-02-27 19:07 UTC, JanGiese commented on requirements.txt
> +ruff==0.1.9
Yes, I think so. Can you maybe paste the PyPi link (or requirements.txt entry)here . I will try it out then, mostlikely on the weekend.

2024-02-27 19:09 UTC, dontinelli commented on .devcontainer.json
> +}
Thank you, was not aware of this.

2024-02-27 19:11 UTC, JanGiese commented
> Thank you a lot, looks great! I only have two questions before I merge:
> 
> 1. In the meanwhile I uploaded fyta_cli to Pypi. Would it make sense to add fyta_cli as a requirement instead of delivering it as part of the integration files? I'm not sure what the best practice is in this respect, but it has an influence on the import-lines.
--> I will test it on the weekend, just send me the link :)
> 2. With regards to maintenance, can just the files in custom_components/fyta be updated or what else has to be considered for future releases? As you may have noticed, I'm currently working on a PR to include fyta as core integration. However, the review process is rather cumbersome. So while I would like to backport some changes and also further develop the custom integration (which might be easier than bringing improvements to core), I do not have the time for extensive additional work.
--> In general, only the custom_components/fyta files need updates for future releases. Dependency updates will be automated via GitHub´s dependabot, which automatically creates PRs.

2024-02-27 19:11 UTC, JanGiese commented on requirements.txt
> +ruff==0.1.9
That was fast 😆

2024-02-27 19:13 UTC, dontinelli commented on requirements.txt
> +ruff==0.1.9
Commit proposal did not work as expected.
`fyta_cli==0.2.3`
https://test.pypi.org/project/fyta-cli/
https://github.com/dontinelli/fyta_cli

2024-02-27 19:15 UTC, dontinelli commented
> > Thank you a lot, looks great! I only have two questions before I merge:
> > 
> > 1. In the meanwhile I uploaded fyta_cli to Pypi. Would it make sense to add fyta_cli as a requirement instead of delivering it as part of the integration files? I'm not sure what the best practice is in this respect, but it has an influence on the import-lines.
> >    --> I will test it on the weekend, just send me the link :)
> > 2. With regards to maintenance, can just the files in custom_components/fyta be updated or what else has to be considered for future releases? As you may have noticed, I'm currently working on a PR to include fyta as core integration. However, the review process is rather cumbersome. So while I would like to backport some changes and also further develop the custom integration (which might be easier than bringing improvements to core), I do not have the time for extensive additional work.
> >    --> In general, only the custom_components/fyta files need updates for future releases. Dependency updates will be automated via GitHub´s dependabot, which automatically creates PRs.

Thank you. If this is ok for you, I will await your test with the requirement (which might need adjustment of the import-lines) before merging.

2024-02-27 20:00 UTC, dontinelli commented
Wow, swift adjustment! 
`fyta_cli` also provides `fyta_exception` and `fyta_connector`. I would therefore delete these files as well from this repository. Agree?

2024-02-27 20:05 UTC, dontinelli commented on custom_components/fyta/__init__.py
> +from .fyta_connector import FytaConnector
```suggestion
from fyta_cli.fyta_connector import FytaConnector
```

2024-02-27 20:05 UTC, dontinelli commented on custom_components/fyta/config_flow.py
> +from .fyta_exceptions import (
```suggestion
from fyta_cli.fyta_exceptions import (
```

2024-02-27 20:05 UTC, dontinelli commented on custom_components/fyta/config_flow.py
> +from .fyta_connector import FytaConnector
```suggestion
from fyta_cli.fyta_connector import FytaConnector
```

2024-02-27 20:05 UTC, dontinelli commented on custom_components/fyta/coordinator.py
> +from .fyta_connector import FytaConnector
```suggestion
from fyta_cli.fyta_connector import FytaConnector
```

2024-02-27 20:05 UTC, dontinelli commented on custom_components/fyta/fyta_connector.py
> +
```suggestion
```
can be deleted from this repository

2024-02-27 20:05 UTC, JanGiese commented
Good Point! But Unfortunately the release does not include the requirement, so when I install it, it can´t find the fyta_cli.
At a first glance, I could also not any info about dependencies in the HACS documentation.
I will try few more things, cause I also want to know how to use dependencies in custom integrations.
Ideas:
1. Include requirements.txt with only fyta_cli in custom_integrations/fyta
2. Refactor release.yml to download fyta_cli and package it with the release artifact

2024-02-27 20:08 UTC, dontinelli commented
> Good Point! But Unfortunately the release does not include the requirement, so when I install it, it can´t find the fyta_cli. At a first glance, I could also not any info about dependencies in the HACS documentation. I will try few more things, cause I also want to know how to use dependencies in custom integrations. Ideas:
> 
>     1. Include requirements.txt with only fyta_cli in custom_integrations/fyta
> 
>     2. Refactor release.yml to download fyta_cli and package it with the release artifact

Ah ok. Based on your deletion of `fyta_client.py` I assumed that it worked. Thank you for clarifying!

2024-02-27 21:01 UTC, dontinelli commented
Based on your commits I assume it now works with including the requirements. Can you please confirm?

2024-02-28 17:29 UTC, JanGiese commented
Hey @dontinelli,
I have figured out, that dependencies for custom integrations need to be placed in the manifest.json to get loaded with the integration. Unfortunately this fails for me with the with the current fyta_cli due to empty values in my sensor. To get around that, I have added a safe_get function to the fyta_cli and created [PR](https://github.com/dontinelli/fyta_cli/pull/9).
So in theory, you can merge this PR, but I was not able to test it end2end. To make a complete test, I would need the above mentioned PR merged and published.

2024-02-28 18:32 UTC, dontinelli commented
> Hey @dontinelli, I have figured out, that dependencies for custom integrations need to be placed in the manifest.json to get loaded with the integration. Unfortunately this fails for me with the with the current fyta_cli due to empty values in my sensor. To get around that, I have added a safe_get function to the fyta_cli and created [PR](https://github.com/dontinelli/fyta_cli/pull/9). So in theory, you can merge this PR, but I was not able to test it end2end. To make a complete test, I would need the above mentioned PR merged and published.

I merged the PR in `fyta_cli` and generated a new release (v0.3). Would be good if you could test before I merge and release, it would be a pity if it doesn't work in practice.

2024-02-28 18:42 UTC, dontinelli commented
> Hey @dontinelli, I have figured out, that dependencies for custom integrations need to be placed in the manifest.json to get loaded with the integration. Unfortunately this fails for me with the with the current fyta_cli due to empty values in my sensor. To get around that, I have added a safe_get function to the fyta_cli and created [PR](https://github.com/dontinelli/fyta_cli/pull/9). So in theory, you can merge this PR, but I was not able to test it end2end. To make a complete test, I would need the above mentioned PR merged and published.

Thank you @JanGiese! I merged PR in fyta_cli and made new release (v0.3). 

> On it, but I get an exception:
> 
> ```
> 2024-02-28 18:29:16.536 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry jan_giese@gmx.de for fyta
> Traceback (most recent call last):
>   File "/home/vscode/.local/lib/python3.11/site-packages/homeassistant/config_entries.py", line 406, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/workspaces/fyta-custom_component/custom_components/fyta/__init__.py", line 36, in async_setup_entry
>     fyta = FytaConnector(username, password, access_token, expiration)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vscode/.local/lib/python3.11/site-packages/fyta_cli/fyta_connector.py", line 41, in __init__
>     self.timezone: ZoneInfo = datetime.timezone.utc if tz == "" else ZoneInfo(tz)
>                               ^^^^^^^^^^^^^^^^^
> AttributeError: type object 'datetime.datetime' has no attribute 'timezone'
> ```
> 
> on this line in fyta_connector.py
> 
> ```python
> self.timezone: ZoneInfo = datetime.timezone.utc if tz == "" else ZoneInfo(tz)
> ```

can you adjust the line as follows: `self.timezone: ZoneInfo = timezone.utc if tz == "" else ZoneInfo(tz)` and add an `import from datetime import timezone` in your local file to test? If this solves the problem, I would backport this to fyta_cli.

2024-02-28 18:49 UTC, JanGiese commented
Did that, which brings me here:
```
current_plant |= {
            "last_updated": self.timezone.localize(
                datetime.fromisoformat(plant_data["sensor"]["received_data_at"]))}
```
with error
```
AttributeError: 'datetime.timezone' object has no attribute 'localize'
```

2024-02-28 18:56 UTC, dontinelli commented
> Did that, which brings me here:
> 
> ```
> current_plant |= {
>             "last_updated": self.timezone.localize(
>                 datetime.fromisoformat(plant_data["sensor"]["received_data_at"]))}
> ```
> 
> with error
> 
> ```
> AttributeError: 'datetime.timezone' object has no attribute 'localize'
> ```
> 
> btw. I hate handling timezones 😆

I guess this is due to the reverse of my change you made in your commit (of which I thought you know what you were doing ;-)). Before I had the following line, which I have not tested, though:
```
        current_plant |= {
            "last_updated": datetime.fromisoformat(
                plant_data["sensor"]["received_data_at"]
            ).astimezone(self.timezone)
        }
```

2024-02-28 19:24 UTC, JanGiese commented
Btw. is there any way I can reach out to you besides github (slack etc.)? Was fun collaborating with you.
(you may want to create a new Tag for the 0.3.0 release in the fyta_cli repo ;))

2024-02-28 19:31 UTC, dontinelli requested changes

2024-02-28 19:31 UTC, dontinelli commented on custom_components/fyta/manifest.json
> +    "fyta_cli==0.3.0"
```suggestion
    "fyta_cli==0.3.1"
```

2024-02-28 19:31 UTC, dontinelli commented on custom_components/fyta/manifest.json
> +    "fyta_cli==0.3.0"
I released a new version of `fyta_cli`, so requirement has to be adjusted.

2024-02-28 19:31 UTC, dontinelli commented on custom_components/fyta/manifest.json
> +  "version": "0.3.1",
Does this have to be in line with the version of fyta_cli? While same version numbers in the beginning might make sense, I would assume that the custom component might have more releases than fyta_cli in the future. Therefore I think we can keep a separate version tree. What do you think?

2024-02-28 19:36 UTC, dontinelli commented
> Btw. is there any way I can reach out to you besides github (slack etc.)? Was fun collaborating with you. (you may want to create a new Tag for the 0.3.0 release in the fyta_cli repo ;))

Indeed, it is fun and I really appreciate your collaboration! For the time being I'm only on discord (dontinelli_51643). I guess one can also directly communicate there?

2024-02-28 20:42 UTC, merged